[package]
name = "bubly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Remove dynamic when release
bevy = {  workspace = true, features = ["dynamic"] }
bevy_rapier2d = "0.19"
rand = "0.8"

